name: Deploy to Multiple Platforms

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  web-deploy:
    name: Deploy Web to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Install dependencies
        working-directory: mobile
        run: npm ci
      
      - name: Build for web
        working-directory: mobile
        run: npm run build:web
      
      - name: Deploy to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: mobile

  mobile-build:
    name: Build Mobile Apps
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Expo
        uses: expo/setup-expo@v2
        with:
          expo-version: latest

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Build Android APK
        working-directory: mobile
        run: |
          npx eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS IPA (if on macOS)
        if: runner.os == 'macOS'
        working-directory: mobile
        run: |
          npx eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}